return sendMessage false when msg.length is zero
splunk/docker-logging-plugin pull request #3
Opened 2018-02-23 22:45 UTC by anushjay

This fix is to not send blank lines to Splunk (buffer length of zero). 
- Ran unit tests.
- Verified manually.

2018-02-23 22:47 UTC, luckyj5 commented
@anushjay Can we merge this PR first to develop?

2018-02-23 22:53 UTC, sharonx commented
I wonder if the empty line is important for "docker logs <container_id>"

With your change, the docker logs output will not have empty lines.

2018-02-26 19:14 UTC, anushjay commented
@sharonx 
If we are worried about missing these messages then we will have to move this condition into the write function EG: postMessages() (or wherever event formation is going to happen based on the new architecture).
This change does reduce some noise. EG: The Splunk startup logs have  ~12 empty lines that get sent to Splunk and it does not look good :). It will be good to avoid those empty lines from showing up.

2018-02-26 19:53 UTC, sharonx commented
I'm okay with doing the event filtering here. Can we log a message (eg: ignore empty line) when it is empty?

2018-03-02 05:17 UTC, dtregonning commented
@sharonx  good call 
@anushjay add a log when the if fails and its a empty line.

2018-03-02 05:18 UTC, dtregonning requested changes
small change in the else branch of the if. Log the fact you have an empty line

2018-03-02 18:51 UTC, anushjay commented
Thanks, @dtregonning and @sharonx that sounds good. I'll reopen this from a branch off of develop.

2018-03-02 18:51 UTC, closed without merging